/* eslint-disable */
export default {
  "key": "footer",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "essayerfenasiussur": "Try FENASIUS on :",
        "web": "Web",
        "ios": "iOS",
        "android": "Android",
        "produits": "PRODUCTS",
        "fenasius": "FENASIUS",
        "pourtoutes": "FOR ALL",
        "pourparticuliers": "FOR INDIVIDUALS",
        "pourgouvernements": "FOR GOVERNMENTS",
        "ensavoirplus": "LEARN MORE +",
        "companie": "COMPANY",
        "entreprise": "ENTERPRISE",
        "carreiere": "CAREERS",
        "contact": "CONTACT",
        "actualites": "NEWS",
        "politiquedeconfidentialite": "Privacy Policy",
        "mentionslegales": "Legal Notice",
        "conditionsdusuage": "Terms of Use",
        "securite": "Security",
        "ressources": "RESOURCES"
      },
      "fr": {
        "essayerfenasiussur": "Essayer FENASIUS sur :",
        "web": "Web",
        "ios": "iOS",
        "android": "Android",
        "produits": "PRODUITS",
        "fenasius": "FENASIUS",
        "pourtoutes": "POUR TOUTES",
        "pourparticuliers": "POUR PARTICULIERS",
        "pourgouvernements": "POUR GOUVERNEMENTS",
        "ensavoirplus": "EN SAVOIR PLUS +",
        "companie": "COMPAGNIE",
        "entreprise": "ENTREPRISE",
        "carreiere": "CARRIÈRE",
        "contact": "CONTACT",
        "actualites": "ACTUALITÉS",
        "politiquedeconfidentialite": "Politique de confidentialité",
        "mentionslegales": "Mentions légales",
        "conditionsdusuage": "Conditions d'utilisation",
        "securite": "Sécurité",
        "ressources": "RESSOURCES"
      },
      "es": {},
      "ja": {},
      "ko": {},
      "ru": {},
      "hi": {},
      "ar": {
        "essayerfenasiussur": "جرب FENASIUS على :",
        "web": "web",
        "ios": "iOS",
        "android": "Android",
        "produits": "منتجات",
        "fenasius": "FENASIUS",
        "pourtoutes": "للجميع",
        "pourparticuliers": "للأفراد",
        "pourgouvernements": "للحكومات",
        "ensavoirplus": "معرفة المزيد +",
        "companie": "الشركة",
        "entreprise": "الشركة",
        "carreiere": "الوظائف",
        "contact": "الاتصال",
        "actualites": "الأخبار",
        "politiquedeconfidentialite": "سياسة الخصوصية",
        "mentionslegales": "إشعار قانوني",
        "conditionsdusuage": "شروط الاستخدام",
        "securite": "الأمان",
        "ressources": "الموارد"
      },
      "zh-Hans": {},
      "zh-Hant": {}
    }
  },
  "localIds": [
    "footer::local::src/content/footer.content.ts"
  ]
} as const;
